name: bociany
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - numpy
  - cython
  - matplotlib
  - pandas
  - geopandas
  - hvplot
  - geoviews
  - movingpandas
  - jupyterlab
  - pysimplegui
  
